### PR TITLE
GoReleaser WIP

### LINKED ISSUE #21: provide arm (arm64/aarch64) builds
It would be useful to be able to run this on a raspberry pi cluster with official builds.

### PR DESCRIPTION
**Pull request by tashian**
I got the Docker images building w/GoReleaser. This still needs:

- [x] the docker username & PAT added as repo secrets, in order to actually push (@dopey)
- [ ] do we need a lint/test job in the workflow?
- [ ] test the release workflow
- [ ] testing of the built images and docker manifest list generated by GoReleaser

Fixes #21.

### CODE REVIEW

**Comment by Jacksondr5** [comment]
Is there anything I can do to help this along?  I'm trying to get step-issuer set up on my Raspberry Pi cluster

**Comment by tashian** [comment]
@dopey I see you've been working on some goreleaser/GH workflow integration lately.
Is it time to revisit this one?
I'd be happy to pair on it with you if you like.

**Comment by dopey** [comment]
@tashian I think we can close this now, yea?

**Comment by dopey** [comment]
@Jacksondr5 Can you let us know if https://hub.docker.com/layers/smallstep/step-issuer/0.6.2-rc4/images/sha256-2effd99809d01f30e040934486b977037165cbee2b95a6a9ad6c775aa015544f?context=repo works for you?

**Comment by tashian** [comment]
yes

**Pull request closed without merging**
