### PR TITLE
Add support fort cert-manager v0.11.0+

### PR DESCRIPTION
**Pull request by maraino**
### Description 
This PR adds support for the new APIs in cert-manager v0.11.0+.

### CODE REVIEW

**Comment by munnerz** [comment]
Upon a cursory glance, the changes in here look good to me 😄 I've not tested this change however, and I'm also not familiar enough to know for sure if you've changed everything that needs changing in your codebase :)

**Comment by nberlee** [comment]
In order to build it, you would need to change the import:
```
diff --git a/provisioners/step.go b/provisioners/step.go
index 847f9f5..3966905 100644
--- a/provisioners/step.go
+++ b/provisioners/step.go
@@ -8,7 +8,7 @@ import (
        "fmt"
        "sync"
 
-       certmanager "github.com/jetstack/cert-manager/pkg/apis/certmanager/v1alpha1"
+       certmanager "github.com/jetstack/cert-manager/pkg/apis/certmanager/v1alpha2"
        capi "github.com/smallstep/certificates/api"
        "github.com/smallstep/certificates/ca"
        api "github.com/smallstep/step-issuer/api/v1beta1"

**Comment by ondrejtomcik** [comment]
Looks good, hope it will be merged soon.

**Comment by ghoben** [comment]
@maraino You should consider #5 @nberlee changes for this too, before you commit

**Comment by maraino** [comment]
@nberlee, @ondrejtomcik, @ghoben I forgot to push one file. 

I didn't have time to test it a lot, so I didn't merge it yet. I should be able to get to this soon. Let me know if you're using this branch, and if you're having any issues.

**Pull request merged**
